window.Bahasa = {
    /* 
        BAGI TEMEN-TEMEN YANG INGIN GANTI TEKSNYA,
        DARI PADA BINGUNG CARI SATU PER SATU DI FILE JAVACRIPTNYA,
        LANGSUNG AJA TEMUKAN DI SINI DAN GANTI TEKSNYA.
    */
    "indonesia": {
        code: "id",
        dashboard: {
            navbarPesan: "pesan",
            navbarRandom: "acak",
            navbarGrup: "grup",
            navbarKiriman: "kiriman",
            navbarAula: "aula",
            optProfil: "profil",
            optTema: "tema",
            optLibrary: "library",
            optLaporkan: "laporkan",
            optKeluar: "keluar",
            notipinLaporkan: "DESKRIPSIKAN HAL MENARIK (BUG/HAL KURANG BAIK) YANG KAMU TEMUKAN",
            notipinTema: "INGIN BERGANTI TEMA?",
            notipinKeluar: "BENERAN MAU KELUAR DARI AKUN KAMU?",
            notipinLaporkan_Sukses: "LAPORAN BERHASIL DIKIRIM!",
        },
        aula: {
            nomore: "TIDAK ADA PROMOSI LAINNYA",
            tombolBuat: "buat promosi",
            inputGambar: "Pilih Gambar",
            inputJudul: "Judul Project",
            inputDeskripsi: "Deskripsi Singkat",
            inputLink: "Link/URL -- https:// --",
            tombolBatal: "BATAL",
            tombolLanjut: "KIRIM",
            notipinFileGambar: "SILAKAN PILIH FOTO YANG YANG MENGGAMBARKAN PROJECT KAMU",
            notipinTipeGambar: "PILIH FILE DENGAN TIPE GAMBAR DONG",
            notipinInput: "HARAP ISI SEMUA BIDANG",
            notipinLink: "HARAP ISI LINK DENGAN FORMAT YANG BENAR",
            notipinSubmit: "PROMOSI TIDAK AKAN HILANG SELAMANYA SETELAH TERKIRIM<br/>TETAP INGIN MELANJUTKAN?"
        },
        cari: {
            judul: "Cari Pengguna",
            inputNama: "Tulis Nama",
            tombolBatal: "BATAL",
            tombolLanjut: "CARI",
            notipinKarakter: "ISI MINIMAL 2 KARAKTER UNTUK MENCARI",
            nomore: "TIDAK ADA HASIL PENCARIAN LAINNYA",
        },
        chat: {
            inputPesan: "Tulis Pesan . . .",
            pesanTerhapus: "Pesan Telah Dihapus",
            kirimVN: "Mengolah Hasil Rekaman...",
            kirimGambar: "Sedang Mengunggah...",
            notipinTipeGambar: "PILIH FILE DENGAN TIPE GAMBAR DONG",
            notipinTarik: "YAKIN INGIN MENARIK PESAN INI?",
        },
        list_grup: {
            nomore: "TIDAK ADA GRUP LAIN YANG TELAH KAMU IKUTI",
            tombolBuat: "BUAT GRUP",
            tombolGabung: "BERGABUNG",
            judulBuat: "Buat Grup",
            judulGabung: "BERGABUNG GRUP",
            inputNama: "Nama Grup",
            inputID: "ID Grup",
            tombolBatal: "BATAL",
            tombolLanjut_Buat: "BUAT",
            tombolLanjut_Gabung: "GABUNG",
            notipinGagal: "TIDAK DAPAT MENEMUKAN GRUP TERSEBUT",
        },
        list_pesan: {
            nomore: "TIDAK ADA HASIL LAINNYA",
        },
        list_post: {
            tombolBuat: "BUAT KIRIMAN",
            notipinHapus: "YAKIN INGIN MENGHAPUS KIRIMAN INI?",
            inputPesan: "Mau Nulis..?",
            notipinTarik: "YAKIN INGIN MENGHAPUS KOMENTAR INI?",
            pilihPublik: "PUBLIK",
            pilihPengikut: "PENGIKUT",
            inputGambar: "Pilih Gambar",
            inputSesuatu: "Tulis Sesuatu",
            tombolBatal: "BATAL",
            tombolLanjut: "KIRIM",
            notipinTipeGambar: "PILIH FILE DENGAN TIPE GAMBAR DONG",
        },
        guild: {
            tombolTutup: "Tutup",
            tombolChat: "Chat",
            tombolKeluar: "Keluar Grup",
            anggota: "Anggota",
            notipinKeluar: "YAKIN INGIN MENGHAPUS/KELUAR DARI GRUP",
            notipinTipeGambar: "PILIH FILE DENGAN TIPE GAMBAR DONG",
        },
        pengguna: {
            tombolIkuti: "Ikuti",
            tombolMengikuti: "Mengikuti",
            tombolChat: "Chat",
            tombolTutup: "Tutup",
            notipinBerhenti: "INGIN BERHENTI MENGIKUTI?",
            pengikut: "Pengikut"
        },
        profil: {
            tombolSelesai: "Selesai",
            pengikut: "Pengikut",
            notipinTipeGambar: "PILIH FILE DENGAN TIPE GAMBAR DONG",
            inputUsername: "Tulis Username",
            inputBio: "Tulis Bio",
            tombolSimpan: "SIMPAN",
            tombolBatal: "BATAL",
            notipinUsername: "ISI MINIMAL BERISI 4 KARAKTER",
        },
        random: {
            judul: "Temukan Pengguna Online Secara Acak!",
            tombolLanjut: "Mulai",
            notipinPengguna: "Tidak ada pengguna aktif ditemukan<br/>Apakah ingin melanjutkan dengan pengguna offline?",
        },
    },
    "english": {
        code: "en",
        dashboard: {
            navbarPesan: "chats",
            navbarRandom: "random",
            navbarGrup: "groups",
            navbarKiriman: "posts",
            navbarAula: "hall",
            optProfil: "profile",
            optTema: "theme",
            optLibrary: "library",
            optLaporkan: "report",
            optKeluar: "logout",
            notipinLaporkan: "DESCRIBE HERE",
            notipinTema: "WANT TO CHANGE THE THEME?",
            notipinKeluar: "LOGOUT NOW?",
            notipinLaporkan_Sukses: "THANK YOU FOR REPORTING!",
        },
        aula: {
            nomore: "THERE'S NO MORE",
            tombolBuat: "create now",
            inputGambar: "Choose Picture",
            inputJudul: "Project's Title",
            inputDeskripsi: "Short Description",
            inputLink: "Link/URL -- https:// --",
            tombolBatal: "CANCEL",
            tombolLanjut: "SUBMIT",
            notipinFileGambar: "PLEASE CHOOSE A PICTURE ABOUT THE PROJCET YOU'VE MADE",
            notipinTipeGambar: "IMAGE FILE ONLY",
            notipinInput: "FILL IN THE BLANKS",
            notipinLink: "PLEASE FILL IN THE LINK WITH THE CORRECT FORMAT",
            notipinSubmit: "THE PROMOTION WILL PERMANENTLY ONLINE AFTER SUBMITTED<br/>CONTINUE ANYWAY?"
        },
        cari: {
            judul: "Find People",
            inputNama: "Type Here",
            tombolBatal: "CANCEL",
            tombolLanjut: "GO",
            notipinKarakter: "WRITE MINIMUM 2 CHARACTERS TO FIND",
            nomore: "NO RESULT FOUND",
        },
        chat: {
            inputPesan: "Type Here . . .",
            pesanTerhapus: "Message Has Been Deleted",
            kirimVN: "Converting Audio File...",
            kirimGambar: "Uploading...",
            notipinTipeGambar: "CHOOSE IMAGE FILE ONLY",
            notipinTarik: "DO YOU WANT TO DELETE THIS MESSAGE?",
        },
        list_grup: {
            nomore: "THERE ARE NO OTHER GROUPS YOU HAVE PARTICIPATED",
            tombolBuat: "CREATE A GROUP",
            tombolGabung: "JOIN A GROUP",
            judulBuat: "Group Creation",
            judulGabung: "Group Join",
            inputNama: "Group Name",
            inputID: "Group ID",
            tombolBatal: "CANCEL",
            tombolLanjut_Buat: "CREATE",
            tombolLanjut_Gabung: "JOIN",
            notipinGagal: "CAN'T FIND THE GROUP",
        },
        list_pesan: {
            nomore: "NO RESULT FOUND",
        },
        list_post: {
            tombolBuat: "CREATE A POST",
            notipinHapus: "DO YOU WANT TO DELETE THIS POST?",
            inputPesan: "Type Here..",
            notipinTarik: "DO YOU WANT TO DELETE THIS COMMENT?",
            pilihPublik: "PUBLIC",
            pilihPengikut: "FOLLOWERS",
            inputGambar: "Choose Picture",
            inputSesuatu: "Type Here",
            tombolBatal: "CANCEL",
            tombolLanjut: "SUBMIT",
            notipinTipeGambar: "CHOOSE IMAGE FILE ONLY",
        },
        guild: {
            tombolTutup: "Close",
            tombolChat: "Chat",
            tombolKeluar: "Leave Grup",
            anggota: "Member(s)",
            notipinKeluar: "ARE YOU SURE YOU WANT TO LEAVE THIS GROUP",
            notipinTipeGambar: "CHOOSE IMAGE FILE ONLY",
        },
        pengguna: {
            tombolIkuti: "Follow",
            tombolMengikuti: "Followed",
            tombolChat: "Chat",
            tombolTutup: "Close",
            notipinBerhenti: "DO YOU WANT TO UNFOLLOW THIS USER?",
            pengikut: "Follower"
        },
        profil: {
            tombolSelesai: "Done",
            pengikut: "Followers",
            notipinTipeGambar: "CHOOSE IMAGE FILE ONLY",
            inputUsername: "Write Username",
            inputBio: "Write Here",
            tombolSimpan: "SAVE",
            tombolBatal: "CANCEL",
            notipinUsername: "WRITE MINIMUM 4 CHARACTERS",
        },
        random: {
            judul: "Find Random Users Online!",
            tombolLanjut: "Find Now",
            notipinPengguna: "No active users found<br/>Do you want to continue with offline users?",
        },
    }
}

/*
    SUBSCRIBE: DEVANKA 761 
    https://www.youtube.com/c/RG761

    IG: " @dvnkz_ "
*/